### ISSUE TITLE
installation: problem with cryptography minimum version

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-oauthclient#100]
As you can see here: https://travis-ci.org/inveniosoftware/invenio-oauthclient/builds/158729080
There is a issue with lowest requirements and python 2.7.

```
CDefError: 'point_conversion_form_t' has no values explicitly defined: refusing to guess which integer type it is meant to be (unsigned/signed, int/long)
```

I think I found the problem and I'll make a PR.

**Comment by jirikuncar** [comment]
Closed via 5098fd6dbf4d8bffe0d2f87719a19370c64dc7c2
