### ISSUE TITLE
models: fix constraints/indexing naming on sqlite/mysql

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauthclient#114]

**Comment by nharraud** [comment]
@egabancho @lnielsen Is it planned to modify the alembic scripts as it was done in 5398bc17376a971527f4f65a47876d5e3965197b or is it a bug? If we start changing existing alembic scripts it means that existing services like Zenodo, CDS and B2SHARE might not be able to migrate using alembic.

I just checked the name of the `fk_oauthclient_remote_token_remote_account ` constraint in B2SHARE 2.0.0. It is named `oauthclient_remotetoken_id_remote_account_fkey`. This name might have been automatically generated by postgresql.

**Comment by lnielsen** [comment]
See discussion in #119
