### ISSUE TITLE
global: move oauthclient into new module structure

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-oauthclient#12]
- [x] Bootstrap module with cookiecutter template.
- [x] Registries -> entry points + register function on extension
- [x] Create extension class
- [x] Config (see example from Invenio-Records)
- [ ] ... (e.g. Flask-BabelEx for ``gettext/_``, User from invenio-accounts)
  - [ ] mark **all** user facing strings in templates with `{{ _(...) }}`
  - [ ] update catalog (pot)
- [x] Fix imports
- [x] Dependencies in setup.py
- [x] Extension + Blueprints in setup.py
- [x] Find solution UserExt/UserInfo
- [x] Load blueprints via entry point
- [x] Settings module (see invenio-accounts/userprofiles)
- [x] Minimal example app
- [x] Python 3 support
- [x] Templates: Move away from base template - see invenio-theme
- [ ] Test: test cover 90%+  
- [ ] upgrade flask-oauthlib version.
- [x] remove [deprecated code](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient%2Fhandlers.py#L262)

**Comment by lnielsen** [comment]
@hachreak Can you update the ticket with the parts that are done? Thanks

**Comment by hachreak** [comment]
I haven't the rigth to modify your ticket T_T
I think you can add them:
 - Load blueprints via [entry points](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/setup.py#L147-L151).
 - Templates: Move away from [base template](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient%2Ftemplates%2Finvenio_oauthclient%2Fsignup.html) - see invenio-theme
 - Dependencies in [setup.py](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/setup.py#L69-L85)
 - (Partially) Find solution [UserExt](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient%2Fmodels.py#L219)/UserInfo

Maybe you can add a new points:
 - upgrade flask-oauthlib version.
 - remove [deprecated code](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient%2Fhandlers.py#L262)

**Comment by jirikuncar** [comment]
@hachreak thanks. I have updated the ticket summary. I was a bit my mistake too :angel:

**Comment by lnielsen** [comment]
Closing as most of this has been done, and I've opened new issues for the rest.
