### ISSUE TITLE
cern: disconnection needs an extra redirect

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-oauthclient#180]
At CERN, the login process using OAuth creates a cookie when on the domain login.cern.ch.
This means that to complete a logout, that cookie needs to be removed.

Invenio-oauthclient cern is missing a redirect to `https://login.cern.ch/adfs/ls/?wa=wsignout1.0` when logging out so that cookie is deleted. Currently, we redirect to the homepage: https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/cern.py#L293

Without this extra step, the cookie is not cleaned.

**Comment by ppanero** [comment]
Problem state:
------------------
- The logout workflow does not pass by the ``disconnect_handler``.
- Flask Security uses Flask Login to logout user. Flask Login [sends a signal](https://github.com/maxcountryman/flask-login/blob/3e521a326696cafbfbebfbb80a2fbffed68e6cf3/flask_login/utils.py#L215) to logout. However, that signal is in the middle of the process and therefore no redirection is possible.

Flask Security:
------------------
- Flask Security provides a configurable logout URL via ``SECURITY_POST_LOGOUT_VIEW``.
- This URL [must have the same domain](https://github.com/mattupstate/flask-security/blob/3e15d06ee82a728d5cc53059fb28406c7bc6e7aa/flask_security/utils.py#L276) .

Possible Solution:
----------------------
- Create a view (add via blueprint in the local app?)
```python
@blueprint.route('/cern/logout')
    def logout():
        """Logout view."""
        return redirect("https://login.cern.ch/adfs/ls/partiallogout.aspx", code=302)
```

And set up ``SECURITY_POST_LOGOUT_VIEW`` to this route.

Behaviour:
-------------
- The "Clean Cookie" website is shown. However the cookie is not properly cleant.
