### ISSUE TITLE
Oauth register should not require email confirmation

### ISSUE THREAD

**Issue by mb-wali** [inveniosoftware/invenio-oauthclient#256]
## Is your feature request related to a problem? Please describe.

As Sysadmin my instance would most likely have both local authentication and remote/OAuth authentication setup.

I would prefer to request an email confirmation from my local authenticated users, but not for my remote/OAuth auth.

Therefore `flask-security` provides a config variable `SECURITY_CONFIRMABLE` upon which the [register_user](https://github.com/mattupstate/flask-security/blob/674b18103fa8734aca71bbd084ea01e3709817ef/flask_security/registerable.py#L25) method will read the configs and decides on sending the user the confirmation email.

## Describe the solution you'd like
Since we are already overriding  [register_user(invenio-accounts)](https://github.com/inveniosoftware/invenio-accounts/blob/ff5f1d9d6adf22ed47f741958ba7dd2712cd3933/invenio_accounts/utils.py#L155) in we can change the behavior of sending the confirmation link.

For example checking `SECURITY_CONFIRMABLE` for local authentication and then adding a new variable to check if we want to send the confirmation email for OAuth register users.

**Comment by ntarocco** [comment]
Addressed by: https://github.com/inveniosoftware/invenio-oauthclient/pull/288
