### ISSUE TITLE
Github: automatically confirm an user logged in with Github

### ISSUE THREAD

**Issue by alejandromumo** [inveniosoftware/invenio-oauthclient#286]
When an user logs in with Github, it is not possible to automatically log in the user. The user fails to authenticate, given that he's not confirmed yet. 

Ideally, logging in with Github would authenticate the user, thus the user would be automatically confirmed and a confirmation e-mail would not be sent.

**Comment by alejandromumo** [comment]
Will be tackled in https://github.com/inveniosoftware/invenio-oauthclient/pull/287 
Can be closed after it's merged

**Comment by ntarocco** [comment]
@alejandromumo can you confirm that this is fixed by https://github.com/inveniosoftware/invenio-oauthclient/pull/288?
