### ISSUE TITLE
docs: explain how to use invenio-oauthclient with an API only application

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-oauthclient#49]
This module is currently used in B2Share. As B2Share does not use the Flask UI provided by Invenio, it loads `invenio-oauthclient` in its api.

The steps explaining how to use `invenio-oauthclient` in an API application need to be documented.

**Comment by lnielsen** [comment]
@nharraud Could you please put some pointers to how you use OAuthClient in B2SHARE so we can document and close this task.
