### ISSUE TITLE
need release to fix OAuthLib version incompatibility

### ISSUE THREAD

**Issue by nharraud** [inveniosoftware/invenio-oauthclient#70]
A release of invenio-oauthclient is needed.

**Problem description:**
 `invenio-oauth2server>=1.0.0a5 ` depends on `Flask-OAuthlib>=0.9.3`

PR #61 also makes this change in `invenio-oauthclient` but its last release still asks for `Flask-OAuthlib>=0.6.0,<0.7`

Thus the two of them cannot be installed together.

**Comment by nharraud** [comment]
I'll make the PR for the new release.

**Comment by jirikuncar** [comment]
See #69
