### ISSUE TITLE
api: stabilise and document

### ISSUE THREAD

**Issue by tiborsimko** [inveniosoftware/invenio-oauthclient#73]
- [ ] check existing API functionality
- [ ] add missing important API functionality
- [ ] check API function signatures and parameters
- [x] enhance API docstrings (`param`, `returns`, `raises`, `versionadded`)
- [x] plug API functions to existing docs

**Comment by lnielsen** [comment]
- How to use from another module
- Scopes
- Grant types
- Require_api_auth
- Require_oauth_scope
- What should a module define?
- Developers: Explain Invenio, FLask, Oauthlib, Invenio call chain
- Best most secure configuration
