### ISSUE TITLE
CERN: CFG_EXTERNAL_AUTH_HIDDEN_GROUPS* config options renaming

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-oauthclient#76]
Rename configuration options starting with `CFG_*` to follow Invenio 3 naming style:

1. `OAUTHCLIENT_CERN_HIDDEN_GROUPS*` - fits the module naming
2. `CERN_HIDDEN_GROUPS*` - just shorter version that fits the name in `contrib` folder

--
cc @inveniosoftware/triagers 
addresses #73

**Comment by switowski** [comment]
+1 for the first version, it's easier to see in which module a given config variable is used.
