### ISSUE TITLE
cern: missing disconnect handler to unlink account

### ISSUE THREAD

**Issue by ioannistsanaktsidis** [inveniosoftware/invenio-oauthclient#82]
This error occurs when logging in via cern. 
It is caused when this method is called: 
https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/cern.py#L236

To reproduce it Sign in, Sign out and then again sign in and the error should appear.

**Comment by lnielsen** [comment]
Seems like the ``invenio_oauthclient.contrib.cern`` needs a disconnect handler (e.g. like [ORCID](https://github.com/inveniosoftware/invenio-oauthclient/blob/master/invenio_oauthclient/contrib/orcid.py#L161-L176))
