### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by RaoOfPhysics** [inveniosoftware/invenio-oauthclient#92]
> OAuth client support is typically used to allow features such as social login (e.g. Sign in with Twitter) and access to resources **owner** by a specific user at a remote service.

should say:

> OAuth client support is typically used to allow features such as social login (e.g. Sign in with Twitter) and access to resources **owned** by a specific user at a remote service.

correct?

**Comment by lnielsen** [comment]
👍
